version: '3.8'
services:
    db:
        image: postgres
        volumes: 
            - supertest:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        container_name: postgres-bet
        ports:
            - 5432:5432
        depends_on: 
            - "jenkins" 

    maildev:
        image: maildev/maildev
        ports:
            - 1080:80
        container_name: maildev-bet
        depends_on: 
            - "jenkins"

    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8081:8080
            - 50000:50000
        container_name: jenkins-bet
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
volumes:
        supertest:
            external: false